@echo off
echo [PWNDORA] Initializing Browser-Native Forensic Workbench...
echo [PWNDORA] Installing dependencies...
call npm install
echo [PWNDORA] Starting local development server...
call npm run dev
pause